# Utilisez l'image NGINX officielle
FROM nginx:1.25.2

# Copiez votre configuration NGINX personnalisée (si nécessaire)
COPY nginx.conf /etc/nginx/nginx.conf

# Copiez les fichiers de votre application Angular compilée dans le répertoire approprié de NGINX
COPY /dist /usr/share/nginx/html

# Exposez le port 80 (par défaut pour NGINX)
EXPOSE 80

# Aucun besoin de CMD car NGINX démarrera automatiquement
