name: Build and Deploy Angular App to App Engine

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npx ng build

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.APP_ENGINE_DEPLOY_KEY }}'

      - name: Print working directory
        run: |
          echo "Current directory: $(pwd)"

      - name: Deploy to App Engine
        id: deploy
        run: |
          gcloud app deploy dist/**
